/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sim_app_jpuccagol_JPGoLCA */

#ifndef _Included_sim_app_jpuccagol_JPGoLCA
#define _Included_sim_app_jpuccagol_JPGoLCA
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     sim_app_jpuccagol_JPGoLCA
	 * Method:    bind
	 * Signature: ([II)Z
	 */
	JNIEXPORT jboolean JNICALL Java_sim_app_jpuccagol_JPGoLCA_bind
	(JNIEnv*, jobject, jintArray, jint);

	/*
	 * Class:     sim_app_jpuccagol_JPGoLCA
	 * Method:    ready
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_sim_app_jpuccagol_JPGoLCA_ready
	(JNIEnv*, jobject);

	/*
	 * Class:     sim_app_jpuccagol_JPGoLCA
	 * Method:    step
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_sim_app_jpuccagol_JPGoLCA_step
	(JNIEnv*, jobject);

	/*
	 * Class:     sim_app_jpuccagol_JPGoLCA
	 * Method:    read
	 * Signature: ([II)Z
	 */
	JNIEXPORT jboolean JNICALL Java_sim_app_jpuccagol_JPGoLCA_read
	(JNIEnv*, jobject, jintArray, jint);

	/*
	 * Class:     sim_app_jpuccagol_JPGoLCA
	 * Method:    write
	 * Signature: ([II)Z
	 */
	JNIEXPORT jboolean JNICALL Java_sim_app_jpuccagol_JPGoLCA_write
	(JNIEnv*, jobject, jintArray, jint);

	/*
	 * Class:     sim_app_jpuccagol_JPGoLCA
	 * Method:    done
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_sim_app_jpuccagol_JPGoLCA_done
	(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif